### PR TITLE
Deque poll argument

### PR DESCRIPTION
**Pull request by KiillThemAll**
Im using poll results in internal queue -> added std::deque& arg variant to poll function

### CODE REVIEW

**Comment by KiillThemAll** [comment]
Im just curious how to pass all builds with -warnings-as-errors...

**Comment by kenneth-jia** [comment]
Hi, @KiillThemAll 
Maybe you don't really need the`pollMessages(int timeoutMs, std::deque<consumer::ConsumerRecord>& output)` interface. How about using the follwing instead?
```
std::vector<consumer::ConsumerRecord> recordsInVector = theCosumer.pollMessages(int timeoutMs);
std::deque<consumer::ConsumerRecord> recordsInDeque;
std::move(recordsInVector.begin(), recordsInVector.end(), recordsInDeque.begin());
```

**Comment by KiillThemAll** [comment]
According to https://en.cppreference.com/w/cpp/algorithm/move there will be additional complexity on moving vector to deque: 
last - first move assignments.
image

**Comment by kenneth-jia** [comment]
> According to https://en.cppreference.com/w/cpp/algorithm/move there will be additional complexity on moving vector to deque: last - first move assignments. image
Exactly, the "Complixity"  is `last-first` move assignments, -- so is the messages processing. If you're interested, could try profiling your app, -- here's not the place could be optimized.

**Comment by KiillThemAll** [comment]
There will be no std::move(recordsInVector.begin(), recordsInVector.end(), recordsInDeque.begin()); at all if we pass deque by reference.
image

**Comment by kenneth-jia** [comment]
> There will be no std::move(recordsInVector.begin(), recordsInVector.end(), recordsInDeque.begin()); at all if we pass deque by reference. image

Hi, @KiillThemAll 
I don't think it's a good idea to expose too many interfaces for people, -- there's already a `std::vector<consumer::ConsumerRecord> poll(std::chrono::milliseconds)`, and that should be enough.
The `poll(std::chrono::milliseconds timeout, std::vector<ConsumerRecord>& output)` should not be there, nor the `poll(std::chrono::milliseconds timeout, std::deque<ConsumerRecord>& output)`,

So, in some later day, I'll submit a PR to remove `poll(std::chrono::milliseconds timeout, std::vector<ConsumerRecord>& output)`...

**Comment by kenneth-jia** [comment]
> So, in some later day, I'll submit a PR to remove `poll(std::chrono::milliseconds timeout, std::vector<ConsumerRecord>& output)`...

The interface has been removed with https://github.com/morganstanley/modern-cpp-kafka/pull/205

**Pull request closed without merging**
